name = "WindowedFunctions"
uuid = "cfdbd23f-b4cc-482b-ad88-e5a2cd5edccd"
repo = "https://github.com/DiademSpecialProjects/WindowedFunctions.jl.git"
keywords = ["rolling", "running", "windowed", "timeseries"]
author = "Jeffrey Sarnoff"
license = "All Rights Reserved"
version = "v0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MuladdMacro =  "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"

[compat]
StatsBase = ">= v0.33"
StatsFuns = "1"
OnlineStats = "1.5"
LogExpFuncgtions = ">= 0.3"
MuladdMacro = ">= 0.2"
SIMD = ">= 3.4"
Static = ">= 0.7"
VectorizationBase = ">= 0.21"
LoopVectorizaiton = ">= 0.12"
PolyesterWeave = ">= 0.1"
Tables = "1.7"
TableOperations ="1.2"
Dictionaries = ">= 0.3.22"
Chain = ">= 0.5"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
