name = "WindowedFunctions"
uuid = "cfdbd23f-b4cc-482b-ad88-e5a2cd5edccd"
repo = "https://github.com/DiademSpecialProjects/WindowedFunctions.jl.git"
keywords = ["rolling", "running", "windowed", "timeseries"]
author = "Jeffrey Sarnoff"
license = "All Rights Reserved"
version = "v0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"

[compat]
Tables = "1.7"
TableOperations ="1.2"
DataFrames = "1"
Arrow = ">= 2.3"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
